export const langConstant={
   en:{
     home:"Home",
     about:"About",
     contact:"Contact",
     playlist:"PlayList",
     logout:"LogOut",
     search:"Search",
     play:"Play",
     info:"info",
     nowplaying:"Now Playing",
     upcomingmovie:"Upcoming Movie's",
     popular:"Popular",
     toprated:"Top Rated",
     gptplaceholder:"What's would you like to watch today",

   },
   hindi:{
     home:"होम ",
     about:"अबाउट",
     contact:"संपर्क",
     playlist:"प्लेलिस्ट",
     logout:"लॉग आउट",
     search:"खोज",
     play:"शुरू",
     info:"जानकारी",
     nowplaying:"चल रही फिल्में",
     upcomingmovie:"आगामी फिल्म",
     popular:"लोकप्रिय",
     toprated:"टॉप रेटेड",
     gptplaceholder:"आज आप क्या देखना चाहेंगे?",
   },
   french:{
     home:"maison",
     about:"à propos",
     contact:"Contact",
     playlist:"Liste de lecture",
     logout:"déconnexion",
     search:"recherche",
     play:"Jouer",
     info:"infos",
     nowplaying:"Lecture en cours",
     upcomingmovie:"Prochainement",
     popular:"Populaire",
     toprated:"Les mieux notés",
     gptplaceholder:"Qu'aimeriez-vous regarder aujourd'hui ?",
   },
   spanish:{
     home:"Hogar",
     about:"Acerca de",
     contact:"Contacto",
     playlist:"Lista de reproducción",
     logout:"Cerrar sesión",
     search:"buscar",
     play:"Jugar",
     info:"información",
     nowplaying:"Ahora jugando",
     upcomingmovie:"Próximas películas",
     popular:"Popular",
     toprated:"Mejor valorados", 
     gptplaceholder:"¿Qué te gustaría ver hoy?",
   },
   russian:{
     home:"Дом",
     about:"О",
     contact:"Контакт",
     playlist:"Список воспроизведения",
     logout:"Выход из системы",
     search:"Поиск",
     play:"Играть",
     info:"информация",
     nowplaying:"Сейчас играет",
     upcomingmovie:"Предстоящие фильмы",
     popular:"Популярный",
     toprated:"Самый рейтинговый",
     gptplaceholder:"Что бы вы хотели посмотреть сегодня?",
   },
}